/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.semester_Project_Dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IP</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.semester_Project_Dsl.Semester_Project_DslPackage#getIP()
 * @model
 * @generated
 */
public interface IP extends Credentials
{
} // IP
