/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.semester_Project_Dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.semester_Project_Dsl.Semester_Project_DslFactory
 * @model kind="package"
 * @generated
 */
public interface Semester_Project_DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "semester_Project_Dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Semester_Project_Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "semester_Project_Dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Semester_Project_DslPackage eINSTANCE = org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SENSORS = 2;

  /**
   * The feature id for the '<em><b>Credentials</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CREDENTIALS = 3;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.VariableImpl
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.SensorImpl
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Pin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__PIN = 1;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.CredentialsImpl <em>Credentials</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.CredentialsImpl
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getCredentials()
   * @generated
   */
  int CREDENTIALS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREDENTIALS__NAME = 0;

  /**
   * The number of structural features of the '<em>Credentials</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREDENTIALS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.SSIDImpl <em>SSID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.SSIDImpl
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getSSID()
   * @generated
   */
  int SSID = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SSID__NAME = CREDENTIALS__NAME;

  /**
   * The number of structural features of the '<em>SSID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SSID_FEATURE_COUNT = CREDENTIALS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.PasswordImpl <em>Password</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.PasswordImpl
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getPassword()
   * @generated
   */
  int PASSWORD = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSWORD__NAME = CREDENTIALS__NAME;

  /**
   * The number of structural features of the '<em>Password</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSWORD_FEATURE_COUNT = CREDENTIALS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.IPImpl <em>IP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.IPImpl
   * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getIP()
   * @generated
   */
  int IP = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP__NAME = CREDENTIALS__NAME;

  /**
   * The number of structural features of the '<em>IP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP_FEATURE_COUNT = CREDENTIALS_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.semester_Project_Dsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.semester_Project_Dsl.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.semester_Project_Dsl.Model#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Model#getVariables()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.semester_Project_Dsl.Model#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensors</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Model#getSensors()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Sensors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.semester_Project_Dsl.Model#getCredentials <em>Credentials</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Credentials</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Model#getCredentials()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Credentials();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.semester_Project_Dsl.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.semester_Project_Dsl.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.semester_Project_Dsl.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.semester_Project_Dsl.Sensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Sensor#getName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.semester_Project_Dsl.Sensor#getPin <em>Pin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pin</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Sensor#getPin()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Pin();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.semester_Project_Dsl.Credentials <em>Credentials</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Credentials</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Credentials
   * @generated
   */
  EClass getCredentials();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.semester_Project_Dsl.Credentials#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Credentials#getName()
   * @see #getCredentials()
   * @generated
   */
  EAttribute getCredentials_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.semester_Project_Dsl.SSID <em>SSID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SSID</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.SSID
   * @generated
   */
  EClass getSSID();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.semester_Project_Dsl.Password <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Password</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.Password
   * @generated
   */
  EClass getPassword();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.semester_Project_Dsl.IP <em>IP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IP</em>'.
   * @see org.xtext.example.mydsl.semester_Project_Dsl.IP
   * @generated
   */
  EClass getIP();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Semester_Project_DslFactory getSemester_Project_DslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__VARIABLES = eINSTANCE.getModel_Variables();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SENSORS = eINSTANCE.getModel_Sensors();

    /**
     * The meta object literal for the '<em><b>Credentials</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CREDENTIALS = eINSTANCE.getModel_Credentials();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.VariableImpl
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.SensorImpl
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
     * The meta object literal for the '<em><b>Pin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__PIN = eINSTANCE.getSensor_Pin();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.CredentialsImpl <em>Credentials</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.CredentialsImpl
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getCredentials()
     * @generated
     */
    EClass CREDENTIALS = eINSTANCE.getCredentials();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREDENTIALS__NAME = eINSTANCE.getCredentials_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.SSIDImpl <em>SSID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.SSIDImpl
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getSSID()
     * @generated
     */
    EClass SSID = eINSTANCE.getSSID();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.PasswordImpl <em>Password</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.PasswordImpl
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getPassword()
     * @generated
     */
    EClass PASSWORD = eINSTANCE.getPassword();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.semester_Project_Dsl.impl.IPImpl <em>IP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.IPImpl
     * @see org.xtext.example.mydsl.semester_Project_Dsl.impl.Semester_Project_DslPackageImpl#getIP()
     * @generated
     */
    EClass IP = eINSTANCE.getIP();

  }

} //Semester_Project_DslPackage
