/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.semester_Project_Dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SSID</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.semester_Project_Dsl.Semester_Project_DslPackage#getSSID()
 * @model
 * @generated
 */
public interface SSID extends Credentials
{
} // SSID
