/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.semester_Project_Dsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.semester_Project_Dsl.Password;
import org.xtext.example.mydsl.semester_Project_Dsl.Semester_Project_DslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Password</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PasswordImpl extends CredentialsImpl implements Password
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PasswordImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Semester_Project_DslPackage.Literals.PASSWORD;
  }

} //PasswordImpl
