/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.semester_Project_Dsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.semester_Project_Dsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class Semester_Project_DslFactoryImpl extends EFactoryImpl implements Semester_Project_DslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static Semester_Project_DslFactory init()
  {
    try
    {
      Semester_Project_DslFactory theSemester_Project_DslFactory = (Semester_Project_DslFactory)EPackage.Registry.INSTANCE.getEFactory(Semester_Project_DslPackage.eNS_URI);
      if (theSemester_Project_DslFactory != null)
      {
        return theSemester_Project_DslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new Semester_Project_DslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Semester_Project_DslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case Semester_Project_DslPackage.MODEL: return createModel();
      case Semester_Project_DslPackage.VARIABLE: return createVariable();
      case Semester_Project_DslPackage.SENSOR: return createSensor();
      case Semester_Project_DslPackage.CREDENTIALS: return createCredentials();
      case Semester_Project_DslPackage.SSID: return createSSID();
      case Semester_Project_DslPackage.PASSWORD: return createPassword();
      case Semester_Project_DslPackage.IP: return createIP();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variable createVariable()
  {
    VariableImpl variable = new VariableImpl();
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sensor createSensor()
  {
    SensorImpl sensor = new SensorImpl();
    return sensor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Credentials createCredentials()
  {
    CredentialsImpl credentials = new CredentialsImpl();
    return credentials;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SSID createSSID()
  {
    SSIDImpl ssid = new SSIDImpl();
    return ssid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Password createPassword()
  {
    PasswordImpl password = new PasswordImpl();
    return password;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IP createIP()
  {
    IPImpl ip = new IPImpl();
    return ip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Semester_Project_DslPackage getSemester_Project_DslPackage()
  {
    return (Semester_Project_DslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static Semester_Project_DslPackage getPackage()
  {
    return Semester_Project_DslPackage.eINSTANCE;
  }

} //Semester_Project_DslFactoryImpl
