/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalSemester_Project_DslParser;
import org.xtext.example.mydsl.services.Semester_Project_DslGrammarAccess;

public class Semester_Project_DslParser extends AbstractAntlrParser {

	@Inject
	private Semester_Project_DslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSemester_Project_DslParser createParser(XtextTokenStream stream) {
		return new InternalSemester_Project_DslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Semester_Project_DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Semester_Project_DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
