/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Semester_Project_DslUiModule extends AbstractSemester_Project_DslUiModule {

	public Semester_Project_DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
