/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.semester_project_dsl.ui.internal.Semester_project_dslActivator;

public class Semester_Project_DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Semester_project_dslActivator.getInstance().getInjector("org.xtext.example.mydsl.Semester_Project_Dsl");
	}

}
