/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Semester_Project_DslStandaloneSetup extends Semester_Project_DslStandaloneSetupGenerated {

	public static void doSetup() {
		new Semester_Project_DslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
