/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSemester_Project_DslScopeProvider extends DelegatingScopeProvider {
}
