/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ide;


/**
 * Use this class to register ide components.
 */
public class Semester_Project_DslIdeModule extends AbstractSemester_Project_DslIdeModule {
}
