/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.Semester_Project_DslRuntimeModule;
import org.xtext.example.mydsl.Semester_Project_DslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Semester_Project_DslIdeSetup extends Semester_Project_DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Semester_Project_DslRuntimeModule(), new Semester_Project_DslIdeModule()));
	}
	
}
